### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by kaqualls** [AcidWeb/CurseBreaker#172] opened 2020-10-11 00:59 UTC
CurseBreaker v3.11.1

When I run the import command I get this error:

CB> import
  Traceback (most recent call last) 
  CurseBreaker.py:184 in start
  CurseBreaker.py:726 in c_import
  CB\Core.py:613 in detect_addons
ValueError: max() arg is an empty sequence

**Comment by AcidWeb** [comment] 2020-10-11 05:45
Yeah. There is a bug in import code that will be fixed in next release.

You can wait for update or provide output of `dir /b` from `AddOns` directory and I will tell you which directory is crashing import.

**Comment by DrewFlyBoy** [comment] 2020-10-12 06:35
I had the same issue. Below is the list of addons from my retail install:

!Swatter
AAP-BfA
AAP-Cata-MoP
AAP-Core
AAP-Legion
AAP-TBC-WotLK
AAP-Vanilla
AAP-WoD
AdiBags
AdiBags_BoE_BoA
AdiBags_Config
AdiBags_Expansion_Trade_Goods
AdiBags_Hearthstones
AdiBags_Legion_Filters
AdvancedInterfaceOptions
ArkInventory
ArkInventoryConfig
ArkInventoryRules
ArkInventoryRules_Example
ArkInventorySearch
Atlas
AtlasLoot
AtlasLoot_BattleforAzeroth
AtlasLoot_BurningCrusade
AtlasLoot_Cataclysm
AtlasLoot_Classic
AtlasLoot_Collections
AtlasLoot_Crafting
AtlasLoot_Factions
AtlasLoot_Legion
AtlasLoot_MistsofPandaria
AtlasLoot_Options
AtlasLoot_PvP
AtlasLoot_WarlordsofDraenor
AtlasLoot_WorldEvents
AtlasLoot_WrathoftheLichKing
Atlas_Arena
Atlas_Battlegrounds
Atlas_BurningCrusade
Atlas_Cataclysm
Atlas_ClassicWoW
Atlas_ClassOrderHalls
Atlas_DungeonLocs
Atlas_Legion
Atlas_MistsofPandaria
Atlas_OutdoorRaids
Atlas_Scenarios
Atlas_Transportation
Atlas_WarlordsofDraenor
Atlas_WorldEvents
Atlas_WrathoftheLichKing
Auc-Advanced
Auc-Filter-Basic
Auc-ScanData
Auc-Stat-Histogram
Auc-Stat-iLevel
Auc-Stat-Purchased
Auc-Stat-Simple
Auc-Stat-StdDev
Auc-Util-FixAH
Auctionator
AutoLootSpec
Azeroth Auto Pilot
BeanCounter
Blizzard_AchievementUI
Blizzard_ArchaeologyUI
Blizzard_ArenaUI
Blizzard_AuctionUI
Blizzard_AuthChallengeUI
Blizzard_BarbershopUI
Blizzard_BattlefieldMinimap
Blizzard_BindingUI
Blizzard_BlackMarketUI
Blizzard_Calendar
Blizzard_ChallengesUI
Blizzard_ClientSavedVariables
Blizzard_Collections
Blizzard_CombatLog
Blizzard_CombatText
Blizzard_CompactRaidFrames
Blizzard_CUFProfiles
Blizzard_DeathRecap
Blizzard_DebugTools
Blizzard_EncounterJournal
Blizzard_GarrisonUI
Blizzard_GlyphUI
Blizzard_GMChatUI
Blizzard_GMSurveyUI
Blizzard_GuildBankUI
Blizzard_GuildControlUI
Blizzard_GuildUI
Blizzard_InspectUI
Blizzard_ItemAlterationUI
Blizzard_ItemSocketingUI
Blizzard_ItemUpgradeUI
Blizzard_LookingForGuildUI
Blizzard_MacroUI
Blizzard_MovePad
Blizzard_ObjectiveTracker
Blizzard_PetBattleUI
Blizzard_PetJournal
Blizzard_PVPUI
Blizzard_QuestChoice
Blizzard_RaidUI
Blizzard_SocialUI
Blizzard_StoreUI
Blizzard_TalentUI
Blizzard_TimeManager
Blizzard_TokenUI
Blizzard_TradeSkillUI
Blizzard_TrainerUI
Blizzard_Tutorial
Blizzard_VoidStorageUI
Blizzard_WowTokenUI
bobSatchels
BodyGuardAway
Cecile_QuickLaunch
Cecile_QuickLaunchAchievements
Cecile_QuickLaunchAddOns
Cecile_QuickLaunchItems
Cecile_QuickLaunchMacros
Cecile_QuickLaunchMounts
Cecile_QuickLaunchPets
Cecile_QuickLaunchProfessions
Cecile_QuickLaunchSocial
Cecile_QuickLaunchSpecGear
Cecile_QuickLaunchSpells
Cecile_QuickLaunchToys
ClassTimer
CQuestCounter
CrossRealmAssist
DailyGlobalCheck
DailyGlobalCheck_Legion_RareMobs
DataStore
DataStore_Containers
DBM-AQ20
DBM-AQ40
DBM-Azeroth
DBM-Azeroth-BfA
DBM-BaradinHold
DBM-BastionTwilight
DBM-BlackTemple
DBM-BlackwingDescent
DBM-Brawlers
DBM-BWL
DBM-CastleNathria
DBM-ChamberOfAspects
DBM-Coliseum
DBM-Core
DBM-CrucibleofStorms
DBM-DefaultSkin
DBM-DMF
DBM-DragonSoul
DBM-EternalPalace
DBM-EyeOfEternity
DBM-Firelands
DBM-GUI
DBM-Hyjal
DBM-Icecrown
DBM-Karazhan
DBM-MC
DBM-Naxx
DBM-Nyalotha
DBM-Onyxia
DBM-Outlands
DBM-Party-BfA
DBM-Party-Shadowlands
DBM-PvP
DBM-Serpentshrine
DBM-StatusBarTimers
DBM-Sunwell
DBM-TheEye
DBM-ThroneFourWinds
DBM-Uldir
DBM-Ulduar
DBM-VoA
DBM-WorldEvents
DBM-ZuldazarRaid
Decursive
DejaCharacterStats
Enchantrix
Enchantrix-Barker
ExRT
GarrisonMissionManager
GatherMate2
GatherMate2_Data
GupPet
HandyNotes
HandyNotes_AzerothsTopTunes
HandyNotes_FieldPhotographer
HandyNotes_HallowsEnd
HandyNotes_HigherLearning
HandyNotes_LegionRaresTreasures
HandyNotes_LunarFestival
HandyNotes_SummerFestival
HandyNotes_TreasureHunter
HandyNotes_WellRead
Hekili
IceHUD
IceHUD_Options
Informant
ItemLinkLevel
LegionWardrobe
LegionWardrobeData
LookingForSatchels
LootAppraiser
MasterPlan
MasterPlanA
MaxCam
MinimapButtonFrame
MinimapButtonFrame_SkinPack
MogIt
MogIt_Artifact
MogIt_Boutique
MogIt_Cloth
MogIt_Leather
MogIt_Mail
MogIt_OneHanded
MogIt_Other
MogIt_Plate
MogIt_Ranged
MogIt_TwoHanded
NeedToKnow
NomiCakes
NPCScan
Omen
Outfitter
Paku_Totems
Paste
Pawn
PersonalLootHelper
PetBattleTeams
PetTracker
PetTracker_Battle
PetTracker_Config
PetTracker_Journal
Prat-3.0
Prat-3.0_Libraries
RaidAssist
RareScanner
RareShare
RareShareMechagon
RareShareNazjatar
RareShare_Uldum
RareShare_Vale of Eternal Blossoms
Rarity
Rarity_Options
Recount
RelicInspector
Routes
SatchelScanner
SavedInstances
Skada
SlideBar
Storyline
StrataFix
Stubby
TidyPlates
TidyPlatesHub
TidyPlatesWidgets
TidyPlates_Graphite
TidyPlates_Grey
TidyPlates_Neon
TidyPlates_Quatre
TidyPlates_ThreatPlates
Titan
TitanBag
TitanClock
TitanCurrenciesMulti
TitanGold
TitanLocation
TitanLootType
TitanPerformance
TitanRecZone
TitanRepair
TitanVolume
TitanXP
TomTom
TooltipItemIcon
ToyPlus
TrackCooldowns
TradeSkillMaster
TradeSkillMaster_AppHelper
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
WorldFlightMap
WorldQuestGroupFinder
WorldQuestTips
WorldQuestTracker
ZPerl
ZPerl_ArcaneBar
ZPerl_CustomHighlight
ZPerl_Options
ZPerl_Party
ZPerl_PartyPet
ZPerl_Player
ZPerl_PlayerBuffs
ZPerl_PlayerPet
ZPerl_RaidAdmin
ZPerl_RaidFrames
ZPerl_RaidHelper
ZPerl_RaidMonitor
ZPerl_RaidPets
ZPerl_Target
ZPerl_TargetTarget
_NPCScan.Overlay

**Comment by AcidWeb** [comment] 2020-10-12 06:52
Problem is caused by mix of incomplete addons in your addon directory. Tommorow I will release a proper fix for this issue.

For now remove `DataStore` and `DataStore_Containers` directories. And install them after import if you really need them.

**Comment by DrewFlyBoy** [comment] 2020-10-12 08:21
That worked. Thank you for the quick response.

**Comment by AcidWeb** [comment] 2020-10-13 12:00
Fixed in 3.12.0.

**Closed by AcidWeb** 2020-10-13 12:00 UTC
Labels: bug
